package com.forgemind.modules.ai.rag;

import com.forgemind.modules.ai.vector.ScoredChunk;
import java.util.List;
import org.springframework.stereotype.Component;

/** Formats retrieved vector chunks into a Markdown payload appended to the LLM prompt. */
@Component
public class PromptAugmenter {

  /**
   * Appends retrieved knowledge chunks to the user's prompt.
   *
   * @param originalPrompt the prompt generated by the agent
   * @param chunks         the chunks retrieved from the vector store
   * @return the combined prompt string
   */
  public String augment(String originalPrompt, List<ScoredChunk> chunks) {
    if (chunks == null || chunks.isEmpty()) {
      return originalPrompt;
    }

    StringBuilder sb = new StringBuilder(originalPrompt);
    sb.append("\n\n--- FORGEMIND KNOWLEDGE BASE CONTEXT ---\n");
    sb.append("The following information was retrieved from the project's vector store and may be relevant to your task:\n\n");

    for (int i = 0; i < chunks.size(); i++) {
      ScoredChunk sc = chunks.get(i);
      sb.append(String.format("### Chunk %d (Source: %s, Score: %.2f)\n", 
          i + 1, sc.chunk().getSourceType(), sc.score()));
      
      // Optionally inject metadata if present
      if (sc.chunk().getMetadata() != null && !sc.chunk().getMetadata().isBlank() && !sc.chunk().getMetadata().equals("{}")) {
         sb.append("Metadata: ").append(sc.chunk().getMetadata()).append("\n");
      }
      
      sb.append("Content:\n");
      sb.append(sc.chunk().getChunkText());
      sb.append("\n\n");
    }

    sb.append("--- END KNOWLEDGE BASE CONTEXT ---\n");
    return sb.toString();
  }
}
