package com.forgemind.modules.ai.rag;

import java.util.UUID;

/**
 * Top-level orchestration component for Retrieval-Augmented Generation.
 *
 * <p>Agents call this to optionally retrieve context from the vector store and augment their
 * prompts before sending them to the LLM. It encapsulates the "master switch" logic (if RAG is
 * disabled globally, it simply returns the original prompt unmodified).
 */
public interface RagOrchestrator {

  /**
   * Semantically searches the project's knowledge base and augments the given prompt with the
   * top retrieved chunks.
   *
   * @param projectId   the project scope for access control
   * @param userPrompt  the base prompt generated by the agent
   * @return the augmented context ready for the LLM
   */
  RagContext augmentPrompt(UUID projectId, String userPrompt);
}
